# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-05-14 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('mod_time', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
